### ISSUE TITLE
Service folder does not exist

### ISSUE THREAD

**Issue by dmat93** [net-ty/mnc_Private-5G#5]
Hi,
"service" folder in the NWDAF/NEP ("../service") is not present in the repository. 
In the following the error during the run of the nwdaf.go (same for nep)

`nwdaf.com/service@v0.0.0-00010101000000-000000000000: replacement directory ../service does not exist`

P.S.
Nice work

**Comment by wwtkddnjsww** [comment]
Hello, 
we are sorry for the late answer. 
There has a branch, mnc-public 5G, which has the service folder and other things. 
Also, it is offered to how to run the program. 

Thank you for using it!!
